### ISSUE TITLE
SCP999 spawn

### ISSUE THREAD

**Issue by GabiRP** [TrickyBestia/SCP-999#5]
The SCP-999 Spawns in the Tutorial Tower

**Comment by trickybestia** [comment]
Is player was a spectator?

**Comment by An4r3w** [comment]
yes, actually spawns in the tower because it's good enough. You can bring him in a place with the RA ; )

**Comment by trickybestia** [comment]
Ok I think @GabiRP is not alive more :c

**Comment by GabiRP** [comment]
:v
