### ISSUE TITLE
Size problem

### ISSUE THREAD

**Issue by An4r3w** [TrickyBestia/SCP-999#8]
when 999 spawns the size from 0.6 becomes 1 after a few seconds

**Comment by trickybestia** [comment]
@An4r3w can you tell more detailed?

**Comment by An4r3w** [comment]
ok

so, I spawn me and I have the size that I had put in the config. After a few seconds, my size returns to normal

**Comment by trickybestia** [comment]
Ok, fixing it...

**Comment by trickybestia** [comment]
Can't reproduce. Maybe fixed.
